#!/bin/bash

delete()
{
    read -p "Username: " username
    if id $username &>/dev/null; then
        deluser --remove-all-files $username
        sed -i """
AllowUsers $username
Match User USERNAME
    ChrootDirectory /home/$username
        """ /etc/ssh/sshd_config
    else
        echo "User does not exist!"
    fi
}
