#!/bin/bash

$1

case $1 in
    "user")
                case $2 in
                        "create")
                                source /usr/local/sbin/user/create
                                create
                                ;;
                        "delete")   
                                source /usr/local/sbin/user/delete
                                delete
                                ;;
                        *)
                                echo "create, delete, ..."
                                ;;
                esac
            ;;
    *)
            echo "user, ..."
            ;;
esac
